name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-world-java/hello-world-java:latest .

      - name: Push Docker Image
        run: |
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-world-java/hello-world-java:latest

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials \
          ${{ secrets.GKE_CLUSTER }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify Cluster Connection
        run: |
          kubectl get nodes

      - name: Display deployment.yaml
        run: |
          cat deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml

      - name: Wait for Deployment to Complete
        run: |
          kubectl rollout status deployment/hello-world-java --timeout=120s

      - name: Check Pods status
        if: always()
        run: |
          kubectl get pods

      - name: Describe Pods
        if: always()
        run: |
          kubectl describe pods

      - name: Check Deployments
        run: |
          kubectl get deployments